### ISSUE TITLE
Other email fail

### ISSUE THREAD

**Issue by sebi-p** [DominicWatts/ContactAttachment#3]
Emails (except contact form) with content type HTML are failing with an empty body.

After a brief debug I found that unless you load the extended TransportBuilder the body will be empty because the Message setPartsToBody is not triggered.
I've solved this in my project by creating a preference for TransportBuilder as well, not just for the Message.
`<preference for="Magento\Framework\Mail\Template\TransportBuilder" type="Xigen\ContactAttachment\Mail\Template\TransportBuilder"/>`

**Comment by DominicWatts** [comment]
I will check. Which version of magento?
