### ISSUE TITLE
Implement or Add Google Recapcha verification

### ISSUE THREAD

**Issue by robertdraghicescu** [DominicWatts/ContactAttachment#4]
Hi,

is there anyway to can add google recaptcha on your module? Right now if I press Submit button and if the Google Recaptcha is on I have an error related with Google Recaptcha verification, because is not exist in the page.

**Comment by vandijkstef** [comment]
A year after date, I had a similar issue. This module overrides the form.phtml template used in a way that it disables the old contact form layout. In my theme I added the following snippet in `contact_index_index.xml`:

``` XML
<referenceBlock name="xigen.contact.attachment">
	<action method="setTemplate">
		<argument name="template" xsi:type="string">
			Magento_Contact::form.phtml
		</argument>
	</action>
</referenceBlock>
```

Additionally, I had to add `enctype="multipart/form-data"` to the form HTML-tag in `form.phtml` and copied the 'attachment' input field from the modules `form.phtml` to my own version. This made it all work. (Running up-to-date Magento 2.3 at this moment)

**Comment by vandijkstef** [comment]
Obviously I also ran into exactly the same issue. The recaptcha is added as a child, but that needs to be passed. Solution for this module is to change in contact_index_index.html

``` XML
<block class="Magento\Contact\Block\ContactForm" name="xigen.contact.attachment" template="Xigen_ContactAttachment::form.phtml"/>
```

into...

``` XML
<block class="Magento\Contact\Block\ContactForm" name="xigen.contact.attachment" template="Xigen_ContactAttachment::form.phtml">
    <container name="form.additional.info"/>
</block>
```

But this can also be done using your custom contact_index_index.xml:

``` XML
<referenceBlock name="xigen.contact.attachment" >
    <action method="setTemplate">
        <argument name="template" xsi:type="string">
            Magento_Contact::form.phtml
        </argument>
    </action>
    <container name="form.additional.info" label="Form Additional Info"/>
</referenceBlock>
```

Note, this will require the following code set in your form.php where you want the captcha to appear (within your form-tags)

```PHP
<?php echo $block->getChildHtml('form.additional.info') ?>
```

**Comment by DominicWatts** [comment]
Only saw the missing XML entry

```xml
<container name="form.additional.info"/>
```

Everything else looked okay.

Should be fixed in https://github.com/DominicWatts/ContactAttachment/tree/1.0.7

Although untested in 2.4
